"""How much of the tree is connected to Wikidata, and where the gaps are.

Three passes produce links of quite different strength, and lumping them into
one "matched" number would be misleading:

1. **P2600** — the Geni profile ID on a Wikidata item. Exact. Nothing to review.
2. **Structural expansion** — walking from a confirmed match along parent,
   spouse and child links and requiring name and date agreement. Strong, but
   inferred.
3. **Name search** — asking Wikidata for the name and scoring the hits. A
   proposal with no relationship behind it, for a human to accept or reject.

So the report counts them separately, and breaks the remainder down by century
and by how far each unmatched person sits from the nearest match — because a
person one step from a match is a plausible next link, and a person twelve steps
away in an 18th-century farming family is not.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field

from .frontier import descendant_counts
from .model import Tree
from .matching import distance_from_matched

__all__ = ["CoverageInput", "render_markdown"]


@dataclass
class CoverageInput:
    tree: Tree
    #: geni_id -> qid, from the exact P2600 join
    by_p2600: dict[str, str] = field(default_factory=dict)
    #: geni_id -> qid, added by structural expansion
    by_expansion: dict[str, str] = field(default_factory=dict)
    #: proposals awaiting review: (geni_id, qid, confidence, how it was found)
    proposals: list[tuple[str, str, str, str]] = field(default_factory=list)

    @property
    def linked(self) -> dict[str, str]:
        return {**self.by_p2600, **self.by_expansion}


def _century(year: int | None) -> str:
    if year is None:
        return "unknown"
    if year < 1000:
        return "before 1000"
    return f"{year // 100 * 100}s"


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    sep = ["---", *["---:"] * (len(header) - 1)]
    return [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(sep) + " |",
        *["| " + " | ".join(r) + " |" for r in rows],
    ]


def _pct(part: int, whole: int) -> str:
    return f"{100.0 * part / whole:.1f}%" if whole else "n/a"


def render_markdown(data: CoverageInput, top_gaps: int = 25) -> str:
    tree = data.tree
    total = len(tree.people)
    linked = data.linked
    proposed_ids = {geni_id for geni_id, _q, _c, _s in data.proposals} - set(linked)

    lines = [
        "# Wikidata coverage",
        "",
        "Generated by `genimerge.coverage` — re-run `python -m genimerge coverage`.",
        "",
        "Three passes produce links of different strength, counted separately",
        "because lumping them together would overstate what is actually known.",
        "",
    ]

    lines += _table(
        ["", "people", "share of tree"],
        [
            [
                "**linked by P2600** (exact Geni ID on the Wikidata item)",
                str(len(data.by_p2600)),
                _pct(len(data.by_p2600), total),
            ],
            [
                "**linked by expansion** (family structure + name + dates)",
                str(len(data.by_expansion)),
                _pct(len(data.by_expansion), total),
            ],
            [
                "**linked, total**",
                str(len(linked)),
                _pct(len(linked), total),
            ],
            [
                "proposed, awaiting review",
                str(len(proposed_ids)),
                _pct(len(proposed_ids), total),
            ],
            [
                "no link and no proposal",
                str(total - len(linked) - len(proposed_ids)),
                _pct(total - len(linked) - len(proposed_ids), total),
            ],
            ["**tree total**", str(total), "100%"],
        ],
    )

    if data.proposals:
        by_confidence = Counter(c for _g, _q, c, _s in data.proposals)
        by_source = Counter(s for _g, _q, _c, s in data.proposals)
        lines += [
            "",
            "## Proposals awaiting review",
            "",
            "Nothing here has been accepted. `out/wikidata/candidates.csv` carries",
            "the evidence for each: which relationship it came through, the name",
            "overlap, and whether the dates agree.",
            "",
        ]
        lines += _table(
            ["confidence", "proposals"],
            [[c, str(n)] for c, n in by_confidence.most_common()],
        )
        lines += ["", "By how they were found:", ""]
        lines += _table(
            ["found via", "proposals"],
            [[s, str(n)] for s, n in by_source.most_common()],
        )

    lines += [
        "",
        "## By century of birth",
        "",
        "Wikidata coverage of a family tree is really coverage of its notable",
        "members, so it should concentrate in the earliest centuries. If it does",
        "not, the reconciliation is missing something.",
        "",
    ]
    per_century_total: Counter = Counter()
    per_century_linked: Counter = Counter()
    for person in tree.people.values():
        bucket = _century(person.birth_year)
        per_century_total[bucket] += 1
        if person.geni_id in linked:
            per_century_linked[bucket] += 1

    def century_key(name: str) -> tuple:
        if name == "unknown":
            return (2, 0)
        if name == "before 1000":
            return (0, 0)
        return (1, int(name[:-1]))

    lines += _table(
        ["born", "people", "linked", "share"],
        [
            [
                bucket,
                str(per_century_total[bucket]),
                str(per_century_linked[bucket]),
                _pct(per_century_linked[bucket], per_century_total[bucket]),
            ]
            for bucket in sorted(per_century_total, key=century_key)
        ],
    )

    lines += [
        "",
        "## How far the unmatched sit from a match",
        "",
        "Family steps to the nearest linked person. One step away is a plausible",
        "next link; twelve steps away in an 18th-century farming family is not,",
        "and no amount of searching will change that.",
        "",
    ]
    distance = distance_from_matched(tree, linked)
    buckets: Counter = Counter()
    for geni_id in tree.people:
        if geni_id in linked:
            continue
        steps = distance.get(geni_id)
        buckets["unreachable" if steps is None else min(steps, 10)] += 1

    lines += _table(
        ["steps from a linked person", "people"],
        [
            [("10 or more" if k == 10 else str(k)) if k != "unreachable" else k, str(n)]
            for k, n in sorted(buckets.items(), key=lambda kv: (kv[0] == "unreachable", kv[0]))
        ],
    )

    counts = descendant_counts(tree)
    gaps = sorted(
        (p for p in tree.people.values() if p.geni_id not in linked),
        key=lambda p: (counts.get(p.geni_id, 0), -(p.birth_year or 9999)),
        reverse=True,
    )[:top_gaps]

    lines += [
        "",
        f"## The {len(gaps)} biggest unlinked people",
        "",
        "Ranked by how many people in this tree descend from them. These are the",
        "links worth the most, because each one anchors a whole branch and gives",
        "the structural expansion somewhere new to walk from.",
        "",
    ]
    lines += _table(
        ["#", "name", "born", "died", "descendants", "steps from a link", "Geni profile"],
        [
            [
                str(i),
                person.display_name or "*(unnamed)*",
                str(person.birth_year or ""),
                str(person.death_year or ""),
                str(counts.get(person.geni_id, 0)),
                str(distance.get(person.geni_id, "—")),
                f"[{person.geni_id}]({person.url})",
            ]
            for i, person in enumerate(gaps, start=1)
        ],
    )

    return "\n".join(lines) + "\n"
