"""Every DATE line in the corpus whose year is later than this one.

Emma, 2026-08-15, deleting the impossible-years work and replacing it:
*"I want you to delete all of the reports and scripts and .md but run a new
report on just future dates."*

So the screen is one thing and nothing else. A date later than today is
**observably** wrong — nobody in a genealogy is born in 2087 — and the whole
population is small enough to look at by eye. Its predecessor also flagged
year-zero dates and, much more loudly, every date the parser could not read,
which buried the finding under 60-odd rows of unrelated noise.

**Dates are parsed by `genimerge.dates.parse_date`, never by hand.** That module
exists because two hand-rolled parsers have already silently dropped all 4,750
negative-year lines in this corpus; `"-73".isdigit()` is `False`. A date this
script cannot read is **skipped and counted**, not reported: unreadable is a
different phenomenon from future, and mixing them is what went wrong before.

Scanned over `exports/` rather than `out/merged.ged`, because the merged file is
generated and any correction has to be made where the data actually lives.

Writes `reports/future-dates.csv`, one row per offending DATE line, and
`reports/future-dates.md`.

    py scripts/build-future-dates.py
"""

from __future__ import annotations

import csv
import sys
from collections import Counter
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from genimerge import dates, identity, sources  # noqa: E402

CSV_OUT = REPO_ROOT / "reports" / "future-dates.csv"
MD_OUT = REPO_ROOT / "reports" / "future-dates.md"

#: Taken from the clock rather than hardcoded, so the screen does not rot.
THIS_YEAR = date.today().year

COLUMNS = [
    "export",
    "line_number",
    "record_xref",
    "geni_id",
    "record_type",
    "event_tag",
    "raw_date",
    "parsed_year",
    "modifier",
    "years_ahead",
    "name",
]


def main() -> int:
    exports = sources.find_exports()
    print(f"{len(exports)} distinct exports, screening for years > {THIS_YEAR}",
          flush=True)

    rows: list[list] = []
    total_dates = 0
    unreadable = 0

    for path in exports:
        xref = record_type = geni_id = name = event_tag = ""
        with open(path, encoding="utf-8", errors="replace") as handle:
            for number, line in enumerate(handle, 1):
                if line.startswith("0 "):
                    parts = line.split()
                    xref = parts[1] if len(parts) >= 2 else ""
                    record_type = parts[2] if len(parts) >= 3 else ""
                    name = event_tag = geni_id = ""
                    if xref.startswith("@") and xref.endswith("@"):
                        match = identity.GENI_ID_RE.match(xref)
                        if match:
                            geni_id = match.group("geni_id")
                    continue
                if line.startswith("1 "):
                    event_tag = line[2:].split(None, 1)[0].strip()
                    if event_tag == "NAME":
                        name = line[6:].strip()
                    continue
                stripped = line.rstrip("\n")
                if not stripped.startswith("2 DATE "):
                    continue

                total_dates += 1
                raw = stripped[7:].strip()
                parsed = dates.parse_date(raw)
                if parsed is None or parsed.year is None:
                    unreadable += 1
                    continue
                if parsed.year <= THIS_YEAR:
                    continue

                rows.append([
                    path.relative_to(REPO_ROOT).as_posix(),
                    number,
                    xref,
                    geni_id,
                    record_type,
                    event_tag,
                    raw,
                    parsed.year,
                    parsed.modifier or "",
                    parsed.year - THIS_YEAR,
                    name,
                ])

    rows.sort(key=lambda r: (-r[7], r[0], r[1]))
    with CSV_OUT.open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(COLUMNS)
        w.writerows(rows)

    people = {r[3] for r in rows if r[3]}
    by_tag = Counter(r[5] for r in rows)
    by_year = Counter(r[7] for r in rows)

    lines = [
        "# Dates in the future",
        "",
        f"Generated by `scripts/build-future-dates.py` over **{len(exports)} "
        f"exports**. Every `DATE` line whose parsed year is later than "
        f"**{THIS_YEAR}**, one row each in `reports/future-dates.csv`.",
        "",
        f"**{len(rows)} lines**, on **{len(people)} distinct people**, out of "
        f"{total_dates:,} `DATE` lines scanned.",
        "",
        f"{unreadable:,} dates could not be parsed and are **not** in this "
        "report. Unreadable is a different phenomenon from future, and the "
        "report this replaces mixed the two.",
        "",
    ]
    if rows:
        lines += ["## By event tag", "", "| tag | lines |", "| --- | ---: |"]
        lines += [f"| `{t}` | {n} |" for t, n in by_tag.most_common()]
        lines += ["", "## By year", "", "| year | ahead by | lines |",
                  "| ---: | ---: | ---: |"]
        lines += [f"| {y} | {y - THIS_YEAR} | {n} |"
                  for y, n in sorted(by_year.items(), reverse=True)]
        lines += ["", "## Every instance", "",
                  "| year | tag | raw | name | geni id | export:line |",
                  "| ---: | --- | --- | --- | --- | --- |"]
        for r in rows:
            lines.append(
                f"| {r[7]} | `{r[5]}` | `{r[6]}` | {r[10]} | `{r[3]}` | "
                f"`{r[0]}`:{r[1]} |")
    else:
        lines.append("No date in the corpus parses to a year later than "
                     f"{THIS_YEAR}.")
    lines.append("")

    MD_OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {CSV_OUT} ({len(rows)} rows) and {MD_OUT}")
    print(f"{len(rows)} future-dated lines on {len(people)} people; "
          f"{unreadable:,} unreadable dates skipped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
