"""The id list `scripts/pathrun.js` requests, minus everyone already harvested.

Prints a `R.ids = [...]` line to paste under the RUN block. Nothing is fetched here; this is
arithmetic over committed files.

⛔ **EVERYTHING THIS NEEDS IS COMMITTED. THE SCRATCHPAD IS NOT A SOURCE.** Ruled 2026-09-15:
*"Session scratchpad should never be used everything should be committed"*.

The history is why the rule is written here. 2026-09-14: the runner lived only in a browser tab,
the tab was lost at 20:33, and ~8,000 requests of infrastructure went with it -- so `pathrun.js`
was put in `scripts/`. **Its target list was left in the session scratchpad**, and on 2026-09-15
that came due: the scratchpad was gone, `find` returned **0 chunk files**, and the campaign could
not be restarted at all. Half the lesson had been applied.

The sources, both committed:

* `reports/unconnected-p2600.tsv` — the population. 262,908 rows, one per disconnected `P2600`
  holder, regenerated by `tree.yml` after every rebuild. The old chunk files were only ever a
  snapshot of this, and the snapshot is what went missing.
* `reports/geni-paths-harvest.tsv` — every path already found, differenced out.

**The 30-day cooldown is honoured**: `last_attempted` is what `attempt_ledger.stamp` writes, and
re-requesting inside the window spends a page load for nothing.

**Re-requesting somebody is not harmful**, which is what makes a lost cursor survivable: Geni
queues the search and an already-answered one costs a 202 and nothing else. The harvest
difference is an optimisation, not a correctness requirement.

    python scripts/build-pathrun-batch.py --count 800 > batch.js
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import os
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
HARVEST = REPO / "reports" / "geni-paths-harvest.tsv"


ID = re.compile(r"\d{10,}")




#: The committed worklist. **The only source.**
WORKLIST = REPO / "reports" / "unconnected-p2600.tsv"


def worklist_ids() -> list:
    """Every disconnected `P2600` holder as `(qid, geni_id)`, in worklist order.

    ⛔ **NOTHING THE CAMPAIGN NEEDS MAY LIVE IN THE SESSION SCRATCHPAD.** Ruled 2026-09-15:
    *"Session scratchpad should never be used everything should be committed"*.

    This script used to read `chunk-NNNN.txt` out of the scratchpad and its own error message
    admitted the flaw -- *"the chunk files are in the session scratchpad, which moves between
    sessions"*. On 2026-09-15 that came due: the scratchpad was gone, `find` returned **0 chunk
    files**, and the campaign could not be restarted at all. The runner had been dead since its
    tab was lost at 20:33 the evening before, and the thing needed to start it again no longer
    existed.

    **That is the same failure as losing the runner itself, one level down.** 2026-09-14 put
    `pathrun.js` in `scripts/` because it had lived only in a browser tab; the list it reads was
    left in the scratchpad, so half the lesson was applied.

    `reports/unconnected-p2600.tsv` IS the population -- 262,908 rows, one per disconnected
    holder, regenerated by `tree.yml` after every rebuild. The chunk files were only ever a
    snapshot of it, and the snapshot is what went missing.

    **The 30-day cooldown is honoured here**: `last_attempted` is what `attempt_ledger.stamp`
    writes, and re-requesting inside the window spends a page load for nothing.
    """
    if not WORKLIST.exists():
        return []
    #: Pairs, not bare ids, because `--order qid` needs the QID and the worklist is the only
    #: place that carries it. Callers that want ids alone take the second element.
    cutoff = (dt.date.today() - dt.timedelta(days=30)).isoformat()
    out = []
    with WORKLIST.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh, delimiter=chr(9)):
            gid = (row.get("geni_id") or "").strip()
            if not gid.isdigit():
                continue
            when = (row.get("last_attempted") or "").strip()
            if when and when > cutoff:
                continue
            out.append((row.get("qid") or "", gid))
    return out


def harvested() -> set:
    """Every id named anywhere in the harvest index — `from`, `to` and the permalink alike.

    Deliberately loose: over-matching only skips a person who would have cost a cheap 202, while
    under-matching re-requests somebody. The asymmetry favours the loose read.
    """
    found = set()
    if HARVEST.exists():
        with HARVEST.open(encoding="utf-8") as fh:
            found.update(gid for line in fh for gid in ID.findall(line))
    found.update(tiny_path_ids())
    return found


#: Where `build-tiny-gedcoms.py` writes one GEDCOM per harvested relationship path. The file is
#: named for the person the chain ENDS at, so its existence is the fact this function wants.
TINY_PATHS = REPO / "exports" / "tiny-paths"
TINY_NAME = re.compile(r"^harvested-path-geni-(\d{10,})-(?:blood|inlaw)\.ged$")


def tiny_path_ids() -> set:
    """Every person a path chain is already held for, read off the filenames in `exports/tiny-paths/`.

    ⛔ **THE TWO RECORDS OF "A PATH WAS FOUND" DISAGREED, AND ONLY THE SMALLER ONE WAS READ.**
    Measured 2026-09-17: **15,606** ids have a chain on disk and `reports/geni-paths-harvest.tsv`
    mentions **5,912**, so **9,802 people whose path this repo already holds were absent from the
    difference** -- eligible for a fresh request every time a batch is built, forever. That is the
    same *re-asks the same people every session* failure the header of `scripts/pathrun.js`
    records, arriving by the other door: that one was about never writing down an ATTEMPT, this
    one is about never writing down a HIT.

    Caught on two collector runs. Jerzy Kreczmar `6000000031564034073` holds a blood chain AND an
    in-law chain and Justyna Kreczmarowa `6000000043823009103` holds an in-law chain; neither id
    appears anywhere in the harvest index.

    Reading the filename rather than the file is deliberate and is the same asymmetry this
    module's `harvested()` already runs on: **over-matching skips somebody, under-matching
    re-requests them**, and the loose read is the cheap side of that trade. Parsing 15,606
    GEDCOMs to learn a fact their names already state would be the expensive way to be no more
    right.
    """
    if not TINY_PATHS.is_dir():
        return set()
    out = set()
    for entry in TINY_PATHS.iterdir():
        m = TINY_NAME.match(entry.name)
        if m:
            out.add(m.group(1))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=800, help="how many ids to emit")
    ap.add_argument("--skip", type=int, default=0, help="how many to pass over first")
    ap.add_argument("--order", choices=("worklist", "qid"), default="worklist",
                    help="worklist order, or ascending numeric QID")
    ap.add_argument("--half", action="store_true",
                    help="start at the midpoint of the order instead of the front")
    args = ap.parse_args()

    every = worklist_ids()
    if not every:
        raise SystemExit("reports/unconnected-p2600.tsv yielded no ids -- rebuild it with "
                         "scripts/build-unconnected-worklist.py")
    done = harvested()
    todo = [(qid, gid) for qid, gid in every if gid not in done]

    #: ⛔ **THE WORKLIST IS NOT IN QID ORDER AND THE CAMPAIGN ASSUMED IT WAS.** It is grouped by
    #: `neighbourhood_size` descending and only ascends by QID *within* a group -- row 2 is
    #: Q106577730, row 100,000 is Q104657505, row 262,908 is Q65799194. Requesting from offset 0
    #: therefore grinds the same end of the population every session. `--order qid` imposes the
    #: order the campaign was described as having, so `--half` lands somewhere untouched.
    if args.order == "qid":
        todo.sort(key=lambda row: (int(row[0][1:]) if row[0][1:].isdigit() else 1 << 62, row[1]))

    skip = args.skip or (len(todo) // 2 if args.half else 0)
    batch = [gid for _, gid in todo[skip:skip + args.count]]
    print("// %d eligible in the worklist, %d already harvested, %d to go"
          % (len(every), len(done), len(todo)))
    print("// order: %s%s" % (args.order, ", starting at the midpoint" if args.half else ""))
    print("// this batch: %d, starting at offset %d" % (len(batch), skip))
    print("R.ids = " + repr(batch).replace("'", '"') + ";")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
