"""Build the *Duplicates and Namesakes* page from the verdicts and the saved screenshots.

    python scripts/build-duplicates-artifact.py

**Emma, 2026-08-25:** *"probably should fucking save this thing ... as it is pretty good and it
will ve good for it"*, then *"Make something that has all of them"*.

The page had been generated by a throwaway script in the session scratchpad, which lives under
`%LOCALAPPDATA%\\Temp` — and her own `CLAUDE.md` rule says Storage Sense deletes that on Windows'
schedule, not ours. So the generator lives here now, and it is **data-driven** rather than
hand-edited: it reads `reports/multi-p2600-verdicts.tsv` and pairs each row with the screenshots
in `Documents\\claude-screenshots\\`, so the next batch of pairs updates the page by re-running
this rather than by editing prose.

**Two populations, kept apart on purpose.** The main sequence is the verdicts — Wikidata items
that really do carry a `P2600` *Geni.com profile ID* for two different Geni profiles. The tail
section is the six pairs opened first, before the population was measured properly: those items
carry **one Geni id or none**, and the second id came from our own structural walk. Their Geni
evidence is real and worth keeping; the claim that Wikidata held two ids was not. Merging the two
sections back together would re-make exactly the mistake the earlier page had to be corrected for.

Screenshots are matched by filename: `<QID>-a-<name>-<geni id>.jpg` and `<QID>-b-…`. Names and
dates come from `reports/display-names.csv` and `reports/derived-facts.csv`, falling back to the
filename when the profile is not in the merge.

Writes `out/duplicates-and-namesakes.html` (2 MB, images inlined as data URIs) and prints the
path to publish.
"""
from __future__ import annotations

import base64
import collections
import csv
import glob
import html
import os
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
csv.field_size_limit(1 << 30)

ROOT = Path(__file__).resolve().parent.parent
SHOTS = Path(os.environ.get("GENI_SHOTS",
                            r"C:\Users\Emma\Documents\claude-screenshots\geni_2026-08-25"))

#: The six opened before the population was measured. Their items carry one Geni id or none.
OUT_OF_SCOPE = {
    "Q101248370": ("Same woman, twice", "Both are Edel Pedersdatter Saltensee, same father, same "
                   "husband. One profile carries <strong>Review Requested Merge</strong> and a "
                   "curator note about &ldquo;a series of really bad merges&rdquo;."),
    "Q102825194": ("Father and son", "Gilbert Motier de La Fayette and his son Antoine. "
                   "<strong>Wikidata carries no Geni id for this item at all</strong>, so the "
                   "opening is to add the right one, not remove a wrong one."),
    "Q100327211": ("Mother and daughter", "Boson&rsquo;s wife and Boson&rsquo;s daughter &mdash; "
                   "your 34th and 33rd great-grandmothers. Wikidata carries only the "
                   "queen&rsquo;s id, and the parent test says the item is about the daughter."),
    "Q101247043": ("Two different women", "Both married a Str&aring;le af Sj&ouml;ared, but "
                   "different men. <code>Q101247040</code> carries those two men, so this family "
                   "has two couples crossed over two items."),
    "Q103775136": ("Unclear", "Both wives of Wolmar von Uexk&uuml;ll, born three years apart, one "
                   "unnamed &mdash; but different houses. Wikidata carries no Geni id here."),
    "Q103568200": ("Unclear", "Both wives of Bernard III de Saint-Valery, one an <code>NN</code> "
                   "placeholder, but the birth estimates barely overlap."),
}

CHIP = {
    "duplicate": ("One person twice", "dup"),
    "likely-duplicate": ("Likely one person", "likely"),
    "siblings": ("Siblings", "sib"),
    "siblings-uncertain": ("Siblings, uncertain", "likely"),
    "father-son": ("Father &amp; son", "kin"),
    "half-sisters": ("Half-sisters", "kin"),
    "different-people": ("Different people", "diff"),
}
ORDER = ["duplicate", "likely-duplicate", "father-son", "half-sisters", "siblings",
         "siblings-uncertain", "different-people"]


def img(path):
    return "data:image/jpeg;base64," + base64.b64encode(Path(path).read_bytes()).decode()


def load_names():
    disp, years = collections.defaultdict(list), {}
    with open(ROOT / "reports" / "display-names.csv", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            d = (row.get("display_name") or "").strip()
            if d:
                disp[row["geni_id"]].append(d)
    with open(ROOT / "reports" / "derived-facts.csv", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            b = (row.get("birth_date_year") or "").strip()
            d = (row.get("death_date_year") or "").strip()
            if b or d:
                years[row["geni_id"]] = f"{b or '?'}&ndash;{d or '?'}"
    return disp, years


def sides(qid, disp, years):
    out = []
    for letter in ("a", "b"):
        hit = sorted(glob.glob(str(SHOTS / f"{qid}-{letter}-*.jpg")))
        if not hit:
            return None
        stem = Path(hit[0]).stem
        m = re.match(rf"{qid}-{letter}-(.*)-(\d+)$", stem)
        pretty, gid = (m.group(1).replace("-", " "), m.group(2)) if m else (stem, "")
        name = " / ".join(dict.fromkeys(disp.get(gid, []))) or pretty
        out.append((gid, name, years.get(gid, ""), hit[0]))
    return out


def card(qid, label, note, verdict, disp, years):
    s = sides(qid, disp, years)
    if not s:
        return ""
    text, cls = CHIP.get(verdict, (verdict.replace("-", " ").title(), "diff"))
    panes = "".join(
        f'<div class="side"><div class="who"><h3>{html.escape(name)[:110]}</h3>'
        f'<p class="dates">{yr}</p>'
        f'<a class="gid" href="https://www.geni.com/people/x/{gid}">{gid}</a></div>'
        f'<a class="shot" href="https://www.geni.com/people/x/{gid}">'
        f'<img loading="lazy" src="{img(path)}" alt="Geni profile page"></a></div>'
        for gid, name, yr, path in s)
    return (f'<article class="case"><header class="case-head">'
            f'<a class="qid" href="https://www.wikidata.org/wiki/{qid}">{qid}</a>'
            f'<span class="chip {cls}">{text}</span>'
            f'<p class="label">{label}</p></header>'
            f'<p class="note">{note}</p><div class="pair">{panes}</div></article>')


CSS = """
:root{--paper:#f2f4f6;--panel:#fff;--ink:#161a20;--muted:#5d6672;--line:#d5dae1;
 --accent:#2d5f8b;--dup:#1d6b73;--likely:#6b6030;--sib:#8a4326;--kin:#5c4f86;--diff:#2f6146;
 --chip-bg:#eef1f5}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
 --paper:#101318;--panel:#171b22;--ink:#e6e9ee;--muted:#98a2b0;--line:#2a313b;--accent:#7db2dd;
 --dup:#6fc4cd;--likely:#c9b96a;--sib:#e0916a;--kin:#a99add;--diff:#7fc3a0;--chip-bg:#1e242d}}
:root[data-theme="dark"]{
 --paper:#101318;--panel:#171b22;--ink:#e6e9ee;--muted:#98a2b0;--line:#2a313b;--accent:#7db2dd;
 --dup:#6fc4cd;--likely:#c9b96a;--sib:#e0916a;--kin:#a99add;--diff:#7fc3a0;--chip-bg:#1e242d}
*{box-sizing:border-box}
body{background:var(--paper);color:var(--ink);
 font:400 16px/1.6 "IBM Plex Sans",system-ui,-apple-system,"Segoe UI",sans-serif;
 margin:0;padding:0 20px 80px}
.wrap{max-width:1080px;margin:0 auto}
header.top{padding:52px 0 28px;border-bottom:2px solid var(--ink)}
h1{font:600 clamp(30px,4.4vw,46px)/1.1 "Newsreader",Georgia,serif;margin:0 0 14px;
 text-wrap:balance;letter-spacing:-.01em}
.stand{font-size:17px;color:var(--muted);max-width:68ch;margin:0}
.stand strong,.stand em{color:var(--ink)}
code{font:400 .88em "IBM Plex Mono",ui-monospace,monospace;background:var(--chip-bg);
 padding:1px 5px;border-radius:2px;color:var(--ink)}
.tally{display:flex;flex-wrap:wrap;gap:10px;margin:24px 0 0;padding:0;list-style:none}
.tally li{background:var(--panel);border:1px solid var(--line);border-radius:3px;
 padding:9px 14px;font-size:13.5px;color:var(--muted)}
.tally b{font:500 19px/1 "IBM Plex Mono",ui-monospace,monospace;color:var(--ink);
 display:block;margin-bottom:3px;font-variant-numeric:tabular-nums}
.finding{background:var(--chip-bg);border-left:3px solid var(--accent);padding:16px 20px;
 margin:30px 0 0;max-width:80ch;border-radius:0 3px 3px 0;font-size:15px;color:var(--muted)}
.finding strong{color:var(--ink)}
h2{font:600 24px/1.2 "Newsreader",Georgia,serif;margin:52px 0 6px;
 padding-top:20px;border-top:1px solid var(--line)}
h2 .n{font:500 15px "IBM Plex Mono",ui-monospace,monospace;color:var(--muted);margin-left:10px}
.blurb{color:var(--muted);font-size:15px;margin:0 0 4px;max-width:80ch}
.case{background:var(--panel);border:1px solid var(--line);border-radius:4px;
 margin:22px 0;padding:22px}
.case-head{display:flex;align-items:baseline;flex-wrap:wrap;gap:12px;margin-bottom:10px}
.qid{font:500 15px/1 "IBM Plex Mono",ui-monospace,monospace;color:var(--accent);
 text-decoration:none;border-bottom:1px solid currentColor;padding-bottom:2px}
.chip{font-size:11.5px;letter-spacing:.09em;text-transform:uppercase;font-weight:600;
 padding:4px 10px;border-radius:2px;background:var(--chip-bg)}
.chip.dup{color:var(--dup)}.chip.likely{color:var(--likely)}.chip.sib{color:var(--sib)}
.chip.kin{color:var(--kin)}.chip.diff{color:var(--diff)}
.label{font:600 17px/1.35 "Newsreader",Georgia,serif;margin:0;flex:1 1 100%}
.note{color:var(--muted);font-size:14.5px;margin:0 0 20px;max-width:84ch}
.note strong,.note em{color:var(--ink)}
.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}
@media (max-width:760px){.pair{grid-template-columns:1fr}}
.side{display:flex;flex-direction:column;gap:9px;min-width:0}
.who h3{font:600 15.5px/1.3 "IBM Plex Sans",sans-serif;margin:0 0 3px;overflow-wrap:anywhere}
.dates{margin:0;font-size:13px;color:var(--muted);font-variant-numeric:tabular-nums}
.gid{font:400 12px "IBM Plex Mono",ui-monospace,monospace;color:var(--accent);
 text-decoration:none;word-break:break-all}
.gid:hover,.qid:hover{text-decoration:underline}
.shot{display:block;border:1px solid var(--line);border-radius:3px;overflow:hidden;
 background:var(--chip-bg)}
.shot img{display:block;width:100%;height:auto}
footer{margin-top:46px;padding-top:22px;border-top:1px solid var(--line);
 color:var(--muted);font-size:14px;max-width:78ch}
a:focus-visible{outline:2px solid var(--accent);outline-offset:3px}
"""

BLURB = {
    "duplicate": "One person, two Geni profiles. The fix is a merge on Geni; the second "
                 "<code>P2600</code> on the item is then correct and stays.",
    "likely-duplicate": "Almost certainly one person, with one fact still in the way.",
    "father-son": "Two generations on one item. One <code>P2600</code> does not belong.",
    "half-sisters": "Two women on one item.",
    "siblings": "Two siblings on one item, usually sharing a name. One <code>P2600</code> does "
                "not belong.",
    "siblings-uncertain": "Read as siblings, but the name test is weak in these cases.",
    "different-people": "Two unrelated people on one item.",
}


def main():
    disp, years = load_names()
    verdicts = list(csv.DictReader(open(ROOT / "reports" / "multi-p2600-verdicts.tsv",
                                        encoding="utf-8"), delimiter="\t"))
    by = collections.defaultdict(list)
    for r in verdicts:
        by[r["verdict"]].append(r)

    body, shown = [], 0
    for v in ORDER:
        rows = by.get(v, [])
        if not rows:
            continue
        label = CHIP.get(v, (v, ""))[0]
        body.append(f'<h2>{label}<span class="n">{len(rows)}</span></h2>'
                    f'<p class="blurb">{BLURB.get(v, "")}</p>')
        for r in sorted(rows, key=lambda r: r["qid"]):
            note = html.escape(r["evidence"]).replace("&#x27;", "'")
            c = card(r["qid"], "", note, v, disp, years)
            if c:
                body.append(c)
                shown += 1

    tail = []
    for qid, (label, note) in OUT_OF_SCOPE.items():
        c = card(qid, label, note, "different-people", disp, years)
        if c:
            tail.append(c)
    if tail:
        body.append('<h2>Opened first, and outside the population'
                    f'<span class="n">{len(tail)}</span></h2>'
                    '<p class="blurb">These six were opened before the population was measured. '
                    'Wikidata carries <strong>one Geni id or none</strong> for each of them &mdash; '
                    'the second id came from our own structural walk, not from Wikidata. The Geni '
                    'evidence below is real; the claim that Wikidata held two ids was not.</p>')
        body.extend(tail)

    n_dup = len(by["duplicate"]) + len(by["likely-duplicate"])
    n_two = len(verdicts) - n_dup

    page = (
        '<title>Duplicates and Namesakes</title>\n'
        '<link rel="preconnect" href="https://fonts.googleapis.com">'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n'
        '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?'
        'family=Newsreader:opsz,wght@6..72,400;6..72,600&'
        'family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">\n'
        f'<style>{CSS}</style>\n<div class="wrap"><header class="top">'
        '<h1>Duplicates and Namesakes</h1>'
        '<p class="stand">Every Wikidata item found carrying a <code>P2600</code> <em>Geni.com '
        'profile ID</em> for <strong>two different Geni profiles</strong> we hold &mdash; with '
        'both profiles opened and screenshotted, and the verdict read off the pages rather than '
        'guessed from the names.</p>'
        '<ul class="tally">'
        f'<li><b>{len(verdicts)}</b>judged</li>'
        f'<li><b>{n_dup}</b>are one person twice</li>'
        f'<li><b>{n_two}</b>are two real people</li>'
        '<li><b>70</b>in the population</li>'
        '</ul>'
        '<div class="finding"><strong>Both things happen, and the fixes are opposite.</strong> '
        'Where the two profiles are one person, Geni holds a duplicate and a merge is the answer '
        '&mdash; the second <code>P2600</code> is then correct. Where they are two people, '
        'Wikidata has joined a father to his son, two brothers, two sisters, or two strangers who '
        'share a name, and a <code>P2600</code> has to come off.'
        '<br><br><strong>The tell is a title only one person can hold.</strong> Ptolemy Apion was '
        'King of Cyrene once; Gediminas was Grand Duke once. Same office, same death year, or the '
        'same name under two alphabets means one person. Where the given names genuinely differ '
        '&mdash; Fryderyk and Fiodor, Raina and Wasylisa &mdash; they are siblings.'
        '<br><br><strong>And three of the duplicates are recorded as their own brother.</strong> '
        'Geni cannot hold one person twice without wiring the two together somehow, and sibling '
        'is what people reach for.</div>'
        '</header>\n' + "\n".join(body) +
        '\n<footer>Screenshots taken 2026-08-25 and kept in '
        '<code>Documents\\claude-screenshots\\</code>. Verdicts and their evidence live in '
        '<code>reports/multi-p2600-verdicts.tsv</code>; the population is '
        '<code>reports/multi-p2600-targets.tsv</code>, built from Wikidata&rsquo;s own '
        '<code>P2600</code> dump so every candidate is an id Wikidata actually asserts. '
        'Rebuild this page with <code>scripts/build-duplicates-artifact.py</code>. '
        'No Wikidata edit has been made or run.</footer></div>')

    dest = ROOT / "out" / "duplicates-and-namesakes.html"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(page, encoding="utf-8")
    print(f"{shown} verdict cards + {len(tail)} out-of-scope cards")
    print(f"wrote {dest}  ({dest.stat().st_size / 1024 / 1024:.2f} MB)")


if __name__ == "__main__":
    main()
