"""The id list `scripts/pathrun.js` requests, minus everyone already harvested.

Prints a `R.ids = [...]` line to paste under the RUN block. Nothing is fetched here; this is
arithmetic over committed files.

⛔ **EVERYTHING THIS NEEDS IS COMMITTED. THE SCRATCHPAD IS NOT A SOURCE.** Ruled 2026-09-15:
*"Session scratchpad should never be used everything should be committed"*.

The history is why the rule is written here. 2026-09-14: the runner lived only in a browser tab,
the tab was lost at 20:33, and ~8,000 requests of infrastructure went with it -- so `pathrun.js`
was put in `scripts/`. **Its target list was left in the session scratchpad**, and on 2026-09-15
that came due: the scratchpad was gone, `find` returned **0 chunk files**, and the campaign could
not be restarted at all. Half the lesson had been applied.

The sources, both committed:

* `reports/unconnected-p2600.tsv` — the population. 262,908 rows, one per disconnected `P2600`
  holder, regenerated by `tree.yml` after every rebuild. The old chunk files were only ever a
  snapshot of this, and the snapshot is what went missing.
* `reports/geni-paths-harvest.tsv` — every path already found, differenced out.

**The 30-day cooldown is honoured**: `last_attempted` is what `attempt_ledger.stamp` writes, and
re-requesting inside the window spends a page load for nothing.

**Re-requesting somebody is not harmful**, which is what makes a lost cursor survivable: Geni
queues the search and an already-answered one costs a 202 and nothing else. The harvest
difference is an optimisation, not a correctness requirement.

    python scripts/build-pathrun-batch.py --count 800 > batch.js
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import os
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
HARVEST = REPO / "reports" / "geni-paths-harvest.tsv"


ID = re.compile(r"\d{10,}")




#: The committed worklist. **The only source.**
WORKLIST = REPO / "reports" / "unconnected-p2600.tsv"


def worklist_ids() -> list[str]:
    """Every disconnected `P2600` holder's Geni id, in worklist order.

    ⛔ **NOTHING THE CAMPAIGN NEEDS MAY LIVE IN THE SESSION SCRATCHPAD.** Ruled 2026-09-15:
    *"Session scratchpad should never be used everything should be committed"*.

    This script used to read `chunk-NNNN.txt` out of the scratchpad and its own error message
    admitted the flaw -- *"the chunk files are in the session scratchpad, which moves between
    sessions"*. On 2026-09-15 that came due: the scratchpad was gone, `find` returned **0 chunk
    files**, and the campaign could not be restarted at all. The runner had been dead since its
    tab was lost at 20:33 the evening before, and the thing needed to start it again no longer
    existed.

    **That is the same failure as losing the runner itself, one level down.** 2026-09-14 put
    `pathrun.js` in `scripts/` because it had lived only in a browser tab; the list it reads was
    left in the scratchpad, so half the lesson was applied.

    `reports/unconnected-p2600.tsv` IS the population -- 262,908 rows, one per disconnected
    holder, regenerated by `tree.yml` after every rebuild. The chunk files were only ever a
    snapshot of it, and the snapshot is what went missing.

    **The 30-day cooldown is honoured here**: `last_attempted` is what `attempt_ledger.stamp`
    writes, and re-requesting inside the window spends a page load for nothing.
    """
    if not WORKLIST.exists():
        return []
    cutoff = (dt.date.today() - dt.timedelta(days=30)).isoformat()
    out = []
    with WORKLIST.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh, delimiter=chr(9)):
            gid = (row.get("geni_id") or "").strip()
            if not gid.isdigit():
                continue
            when = (row.get("last_attempted") or "").strip()
            if when and when > cutoff:
                continue
            out.append(gid)
    return out


def harvested() -> set:
    """Every id named anywhere in the harvest index — `from`, `to` and the permalink alike.

    Deliberately loose: over-matching only skips a person who would have cost a cheap 202, while
    under-matching re-requests somebody. The asymmetry favours the loose read.
    """
    if not HARVEST.exists():
        return set()
    with HARVEST.open(encoding="utf-8") as fh:
        return {gid for line in fh for gid in ID.findall(line)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--count", type=int, default=800, help="how many ids to emit")
    ap.add_argument("--skip", type=int, default=0, help="how many to pass over first")
    args = ap.parse_args()

    every = worklist_ids()
    if not every:
        raise SystemExit("reports/unconnected-p2600.tsv yielded no ids -- rebuild it with "
                         "scripts/build-unconnected-worklist.py")
    done = harvested()
    todo = [gid for gid in every if gid not in done]

    batch = todo[args.skip:args.skip + args.count]
    print("// %d eligible in the worklist, %d already harvested, %d to go"
          % (len(every), len(done), len(todo)))
    print("// this batch: %d, starting at offset %d" % (len(batch), args.skip))
    print("R.ids = " + repr(batch).replace("'", '"') + ";")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
