"""Turn saved Geni `/path/` pages into path TSVs, and measure the hit rate.

The other half of `scripts/build-isolate-path-targets.py`. That one writes the URLs; the
browser fetches them; this one reads what came back.

**What a hit and a miss look like.** A hit renders the relationship pathway --- anchors
inside ``span.segment > span.name``, which `genimerge.genipage` already parses and which
`paths/isolate-geni-*.tsv` was built from. A miss is Geni saying the two profiles are not
connected, and it carries **no segments at all**. So the discriminator is the parsed step
count, and the threshold is deliberate: a page yielding fewer than `MIN_STEPS` rows is a
miss rather than a one-step path, because the `from` profile alone is a segment on both.

**The hit rate is the whole point of the pilot.** Emma's own batches ran **34-39%** for
academics filtered by occupation and **92%** for Nordic academics, so where the general
population lands decides whether a 185,327-target campaign is worth its request budget.

**Both path types, always --- Emma, 2026-09-02.** A target counts as reached if *either*
type came back. `blood` follows descent only; `inlaw` allows marriage steps and reaches
people no blood path can, so the per-type columns are worth reading separately --- if
`inlaw` adds little, the campaign halves its fetches.

**Page naming.** `<geni_id>-<blood|inlaw>.html`, the same blob-of-`outerHTML` capture
`scripts/sweep-scraped-pages.sh` already files, with the type appended so the two do not
collide. A bare `<geni_id>.html` is read as `blood`.

**This has NOT been run against a real `/path/` page.** The parser is the one that built the
663 existing paths, and the path page is where that panel lives, but no page of this exact
shape has been fetched --- Geni is not reachable from the session this was written in. The
first pilot page is the thing that establishes it, and a run reporting 0 steps on every page
means the markup differs, not that nothing is connected.

    python scripts/harvest-isolate-paths.py [--pages DIR] [--write-paths]

`--write-paths` writes `paths/isolate-<qid>-<kind>.tsv` for every hit. Without it the run
only measures, which is what a pilot wants before 185k of anything is committed to.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from genimerge import genipage  # noqa: E402

csv.field_size_limit(10_000_000)

PAGES = REPO / "geni-paths"
PILOT = REPO / "reports" / "isolate-path-pilot.tsv"
RESULTS = REPO / "reports" / "isolate-path-pilot-results.tsv"
PATH_TYPES = ("blood", "inlaw")

# `from` and `to` are both segments on a rendered path, so two rows is the shortest real
# path and anything under that is Geni reporting no connection.
MIN_STEPS = 2


def read_page(p: Path) -> list:
    raw = p.read_text(encoding="utf-8", errors="replace")
    return genipage.parse_relationship_path(genipage.html_of_saved_page(raw))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pages", default=str(PAGES), help="directory of saved path pages")
    ap.add_argument("--write-paths", action="store_true", help="also write paths/*.tsv for hits")
    args = ap.parse_args()

    pages = Path(args.pages)
    if not PILOT.exists():
        print(f"no {PILOT.relative_to(REPO)} --- run build-isolate-path-targets.py", file=sys.stderr)
        return 1

    targets = list(csv.DictReader(open(PILOT, encoding="utf-8"), delimiter="\t"))
    rows = []
    for t in targets:
        gid, qid = t["geni_id"], t["qid"]
        row = {
            "qid": qid,
            "geni_id": gid,
            "label": t["label"],
            "in_nordic_roster": t["in_nordic_roster"],
        }
        for kind in PATH_TYPES:
            candidates = [pages / f"{gid}-{kind}.html"]
            if kind == "blood":
                candidates.append(pages / f"{gid}.html")
            page = next((c for c in candidates if c.exists()), None)
            if page is None:
                row[f"{kind}_steps"] = ""
                continue
            links = read_page(page)
            row[f"{kind}_steps"] = len(links)
            if args.write_paths and len(links) >= MIN_STEPS:
                out = REPO / "paths" / f"isolate-{qid.lower()}-{kind}.tsv"
                header = (
                    f"# Geni relationship path to {t['label'] or qid} ({kind})\n"
                    f"#\n"
                    f"# GENERATED by scripts/harvest-isolate-paths.py from {page.name}.\n"
                    f"# Do not hand-edit: re-run the command instead.\n"
                )
                out.write_text(genipage.to_tsv(links, header=header), encoding="utf-8")
        rows.append(row)

    fetched = [r for r in rows if r["blood_steps"] != "" or r["inlaw_steps"] != ""]

    def hit(r, kind):
        v = r[f"{kind}_steps"]
        return v != "" and v >= MIN_STEPS

    for r in rows:
        r["reached"] = "1" if (hit(r, "blood") or hit(r, "inlaw")) else "0"

    RESULTS.parent.mkdir(parents=True, exist_ok=True)
    tmp = RESULTS.with_suffix(".tsv.tmp")
    cols = ["qid", "geni_id", "label", "in_nordic_roster", "blood_steps", "inlaw_steps", "reached"]
    with open(tmp, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols, delimiter="\t", lineterminator="\n")
        w.writeheader()
        for r in sorted(rows, key=lambda r: r["qid"]):
            w.writerow(r)
    tmp.replace(RESULTS)

    print(f"targets in roster : {len(rows)}", file=sys.stderr)
    print(f"pages fetched     : {len(fetched)}", file=sys.stderr)
    if not fetched:
        print("nothing fetched yet --- no hit rate to report", file=sys.stderr)
        return 0

    reached = sum(1 for r in fetched if r["reached"] == "1")
    print(f"reached (either)  : {reached}/{len(fetched)} = {reached / len(fetched):.0%}", file=sys.stderr)
    for kind in PATH_TYPES:
        tried = [r for r in fetched if r[f"{kind}_steps"] != ""]
        if tried:
            h = sum(1 for r in tried if hit(r, kind))
            print(f"  {kind:<6}          : {h}/{len(tried)} = {h / len(tried):.0%}", file=sys.stderr)
    only_inlaw = sum(1 for r in fetched if hit(r, "inlaw") and not hit(r, "blood"))
    print(f"  reached ONLY by inlaw: {only_inlaw}", file=sys.stderr)
    steps = [r["blood_steps"] for r in fetched if hit(r, "blood")]
    if steps:
        print(f"  blood steps: median {sorted(steps)[len(steps) // 2]}, max {max(steps)}", file=sys.stderr)
    print(f"wrote {RESULTS.relative_to(REPO)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
